### PR TITLE
Update default branch name

### LINKED ISSUE #171: Migrate `master` to `main` branch
GitHub makes this process (on the Git side) fairly simple. However, there are a number of places in the code that need updating too:

 - [ ] [development_and_git.md](https://github.com/HackSoc/hacksoc.org/blob/master/docs/development_and_git.md)
 - [ ] [unittest.yaml](https://github.com/HackSoc/hacksoc.org/blob/master/.github/workflows/unittest.yaml) (needs `master` removing)

### PR DESCRIPTION
**Pull request by sersorrel**
closes #171

### CODE REVIEW

**Comment by FromAnkyra** [comment]
is it worth to wait until the consitution pr is merged so you can change the link in 2021-02-26-agm in this PR or should that be in a separate pull request?

**Comment by sersorrel** [comment]
the constitution branch is renamed already, i just need approval from someone else before i can merge the pr updating the readme :upside_down_face:

**Comment by FromAnkyra** [comment]
@sersorrel yup, deleted the comment because i realised i was incapable of reading, sorry about that

**Comment by sersorrel** [comment]
til github will add new comments after you load the page, but apparently not delete them

**Review by FromAnkyra — APPROVED** [review]
dunno how much you should trust my judgement given the mistake i made earlier, but I did go through and check stuff and it all seemed fine

**Pull request merged**
