### PR TITLE
Backend improvements - BREAKING CHANGES

### PR DESCRIPTION
**Pull request by LukeMoll**
Headline feature of this PR is moving from the `flask` CLI interface to a new `hacksoc_org` one, provided by cli.py and `argparse`. Having full control over the CLI will allow arguments to be passed during development; chiefly being able to control the markdown implementation as we explore alternatives to the non-commonmark-compliant `markdown2`.

Other features include:
 - `build_datetime()` global function to display the datetime at build-time

## TODO
 - [x] Re-document CLI and installation process

## Testing and migration notes
Recommended to:
 - Delete your venv and create a new one
 - Upgrade pip (`pip install --upgrade pip`)
 - Install with the new method (`pip install -e .`)

### CODE REVIEW

**Comment by sersorrel** [comment]
```
$ hacksoc_org --help                                                                                                                                                                                                                    interactive-python3-3.7.10-environment
Traceback (most recent call last):
  File "/nix/store/gk615qkf3hp29h5l9gx0hcmrrjz4sx1z-python3.7-hacksoc_org-1.0.0/bin/.hacksoc_org-wrapped", line 6, in <module>
    from hacksoc_org.cli import main
  File "/nix/store/d6sza42gn3m4l2xkac93ccl3vsl1v57p-python3-3.7.10-env/lib/python3.7/site-packages/hacksoc_org/__init__.py", line 32, in <module>
    with open(path.join(ROOT_DIR, "templates", "context.yaml"), encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/d6sza42gn3m4l2xkac93ccl3vsl1v57p-python3-3.7.10-env/lib/python3.7/site-packages/templates/context.yaml'
```

uh

i realise that _nix_

however

is this: you need a MANIFEST.in

**Comment by sersorrel** [comment]
ok ugh
i think the way to solve this is ultimately gonna be to put the `templates` directory inside `hacksoc_org`, then stick `recursive-include hacksoc_org/templates` or similar in a MANIFEST.in
(but i do not know for sure and i don't have brain or really ability to test it, sorry)
python packaging: it is Bad

**Comment by LukeMoll** [comment]
Uh I just ran pip install --upgrade pip and it works without a setup.py

**Comment by LukeMoll** [comment]
## For development
This works fine with `--editable`/`-e`, and there's no sensible use case for installing a non-editable package.

## For production
In the future, it could be desirable to run `pip install git+https://github.com/hacksoc/hacksoc.org.git` on production.

**Pull request merged**
