### PR TITLE
Update about.html.jinja2

### PR DESCRIPTION
**Pull request by markspolakovs**
Update committee membership and years of study

### CODE REVIEW

**Comment by markspolakovs** [comment]
Verified renders correctly locally:

image

**Review by PYRiTEmonark — APPROVED** [review]
Unsure what happened to that last line but otherwise LGTM

**Comment by sersorrel** [comment]
last line of the diff is just "this file didn't have a terminal newline, now it does"

the OMs are no longer sorted alphabetically by name, was that deliberate? we should probably decide on a convention and document it somewhere (if only as a comment in the file)

**Comment by sersorrel** [comment]
merging this as-is because it's been a month and i'm tired of having to remember that the about page is out-of-date

**Pull request merged**
