### PR TITLE
Improve minutes.html

### LINKED ISSUE #96: Inconsistent display on talks.html
Currently the heirarchy on talks.html is as follows:

```
<h2> Spring (current) Term talks
   <h3> Talk title
<h2> Past talks
   <h3> Autumn Term 2019
      <h4> Talk title
<h2> Giving a talk
```

Semantically and stylistically, this has some problems (as raised in PR #74 ). Ideally the talk titles would always be the same heading level **hn,** and so the "containing" parent heading would also always be the same **h(n-1)**. 

As part of this fix, each term of past talks could be wrapped in a `<details>`/`<summary>` pair to mean that Giving A Talk is easier to scroll to. Additionally, if Giving a Talk is given an `id`, then creating a link to talks.html#giving-a-talk would be a good way to make the information more easily accessed.

### PR DESCRIPTION
**Pull request by LukeMoll**
## Changes
 - Organise minutes into subfolders by committee
 - Collapsible sections per-committee in reverse chronological order
 - Minutes listed within each section in reverse chronological order
 - Removed spaces from filenames
    - causes issues in browsers that don't automatically URL-encode these spaces
    - looking at you, firefox

## For attention of reviewers
 - Please check that minutes are categorised in the correct committee year.
 - Feedback also wanted on the "Constitution" section; is this the best way to link (ie <a href>here</a>) to the constitution?

fixes #96 (Android!Chrome downloading PDFs not addressed, is this still an issue?)

### CODE REVIEW

**Comment by LukeMoll** [comment]
Screenshot_20210923_154856
Currently looks like this

**Comment by FromAnkyra** [comment]
It is not overly obvious to me that the headings are clickable to drop down - the triangles are very small and when I have it as half-screen they're very much on the edge of the screen, meaning they're barely visible. Also, the cursor doesn't change when I pass over it, nor is there any change to the text. I get that it feels slightly wrong because it's not a hotlink, but I think there should be at least _some_ indicator imo

minutes pic

Also, I will admit that until I looked at the code I genuinely did not see `Click on the titles to expand a preview of minutes. Click [pdf] to download or open the full minutes in a new tab.`

I'd recommend either changing the colour from the de-emph colour or make the font a bit bigger/thicker

aside from that it looks pretty good? firefox appreciates the lack of space in the url

**Comment by FromAnkyra** [comment]
additionally, is there a way to test if this retains the "android tries to download everything at once" bug? It would be nice to address everything in #112

**Comment by LukeMoll** [comment]
My screenshots won't include mouse pointers >_> but the committee years now go underlined and have the "pointer" cursor applied when hovering, (consistent with the minutes links). The arrows are now larger and match the font colour, and the text has been put in a normal paragraph under the Minutes heading.
Screenshot_20210924_104448

And at large display sizes, theres now some margin between the marker and the viewport edge.
image

**Review by FromAnkyra — APPROVED** [review]
that looks very good

**Comment by LukeMoll** [comment]
Now has a new ~red arm~ look, with:
 - Minutes using the same `<details>` element as the committee years
 - Human-readable date format replacing ISO format.
image

**Pull request merged**
