### PR TITLE
Tweaks to talks.html

### LINKED ISSUE #96: Inconsistent display on talks.html
Currently the heirarchy on talks.html is as follows:

```
<h2> Spring (current) Term talks
   <h3> Talk title
<h2> Past talks
   <h3> Autumn Term 2019
      <h4> Talk title
<h2> Giving a talk
```

Semantically and stylistically, this has some problems (as raised in PR #74 ). Ideally the talk titles would always be the same heading level **hn,** and so the "containing" parent heading would also always be the same **h(n-1)**. 

As part of this fix, each term of past talks could be wrapped in a `<details>`/`<summary>` pair to mean that Giving A Talk is easier to scroll to. Additionally, if Giving a Talk is given an `id`, then creating a link to talks.html#giving-a-talk would be a good way to make the information more easily accessed.

### PR DESCRIPTION
**Pull request by LukeMoll**
Various improvements to the talks page:
 - Removed `<b>` and `<br>`
 - Past talks are collapsed by term into `<details>` boxes 
 - Moved "past talks" above all current and past talks so it can be found more easily.

Screenshot: large heading "Past talks", followed by smaller collapsed section (indicated by a right-facing triangle) "Summer Term 2019/20", and an expanded section (indicated by a downwards-facing triangle) "Spring Term 2019/20".

Getting rid of `<br>` does remove some vertical space between talks, imo with the added pre-H3 space this is still fine, but if we want the old space back then it's easily done with CSS rather than using that old tag.
Screenshot: side-by-side of the spacing between talk sections. On the left, "before" with about 1.5 line-heights between the end of the talk abstract and the following talk's title. On the left, "after" reduced to about a single line-height.

Still **TODO** before review:
- [ ] `<summary>` doesn't render correctly in mobile view
- [ ] Would be nice to resolve #96 WRT different heading levels for current and past talks
- [ ] Add `<h2>Talks</h2>`? The way that "HackSoc runs talks..." begins without a heading looks kinda weird
Screenshot: top of the webpage in question. The first paragraph begins immediately below the website header, in contrast to the next paragraph, which begins after a heading.

Obviously the "Giving a talk" content isn't correct and probably won't be for the next term or two, that probably deserves a separate issue/PR to address it.

Welcoming any feedback or other frontend suggestions for this page.

### CODE REVIEW

**Comment by sersorrel** [comment]
something like "Upcoming talks" as a heading above the current term would solve the heading problem, i guess.

+1 on adding `<h2>Talks</h2>` at the top.

**Comment by LukeMoll** [comment]
With regards to 
>  `<summary>` doesn't render correctly in mobile view

so that I don't forget, the headings are set to `width: 100%;` which means it wraps onto a different line to the `<details>` triangle
https://github.com/HackSoc/hacksoc.org/blob/985e95de74f7acd623c7c9d09081df0fe9f120a2/static/style_2017.css#L171

Mobile view of collapsed sections, the section heading appears on a separate line to the triangle that indicates the section being open/closed. This is in contrast to the desktop, where both appear on the same line

**Comment by LukeMoll** [comment]
I wonder if <h2>Talks</h2> sets a precedent that we should have titles on the rest of our pages (minutes, about us).

**Comment by LukeMoll** [comment]
I guess having only one `<h3>[current term]</h3>` underneath a `<h2>Upcoming talks</h2>` feels kinda redundant.

**Comment by LukeMoll** [comment]
This PR needs updating from master as the upstream has changed dramatically while this was in WIP

**Comment by LukeMoll** [comment]
Closed in favour of #169

**Pull request closed without merging**
