### PR TITLE
Tweaks to talks.html (new website)

### LINKED ISSUE #96: Inconsistent display on talks.html
Currently the heirarchy on talks.html is as follows:

```
<h2> Spring (current) Term talks
   <h3> Talk title
<h2> Past talks
   <h3> Autumn Term 2019
      <h4> Talk title
<h2> Giving a talk
```

Semantically and stylistically, this has some problems (as raised in PR #74 ). Ideally the talk titles would always be the same heading level **hn,** and so the "containing" parent heading would also always be the same **h(n-1)**. 

As part of this fix, each term of past talks could be wrapped in a `<details>`/`<summary>` pair to mean that Giving A Talk is easier to scroll to. Additionally, if Giving a Talk is given an `id`, then creating a link to talks.html#giving-a-talk would be a good way to make the information more easily accessed.

### PR DESCRIPTION
**Pull request by LukeMoll**
#123 had too many differences with HEAD so it was cleaner to replicate the changes here. 

Fixes #96.

### CODE REVIEW

**Comment by LukeMoll** [comment]
**NB:** 48d34aa changes the `format_date` function in filters.py so that dates now display as `2nd January, 2022`. This is also used for talks (sans the year)

Screenshot_20210924_124939

**Comment by sersorrel** [comment]
smallest of nits:

- "At the request of the speaker, this talk will not be recorded." s/will not be/was not/, imo
- the `<details>` don't have the same cursor:pointer or underline effects as the ones on the minutes page, idk if that's a thing that will sort itself once this is merged? not enough brain to work out where that new styling for the minutes page lives
- the `<hr>` between "Giving a talk" and the list of past talks doesn't look awesome imo (might look better if there was text under the noticebox? vague memory of someone pointing out that there was text there at some point)

**Comment by LukeMoll** [comment]
There was text, it's a content issue but it'd be nice to have that back
It's intended to separate this term's talks from the previous terms' talks (without problematic asymmetric headings), possibly giving it non-default styling would help that

**Comment by LukeMoll** [comment]
Documentation of talk() macro required @LukeMoll

**Comment by LukeMoll** [comment]
Screenshot_20210924_194807
Have updated spacing a bit, now features same hover-over actions as in new minutes.html

**Review by sersorrel — APPROVED** [review]
have not tested that it builds nor looked in any detail at the code you've added since my last comment, but that screenshot looks good to me

**Comment by LukeMoll** [comment]
@LukeMoll talks.html is now no longer a "simple page"

**Comment by LukeMoll** [comment]
@LukeMoll Also current CSS on minutes.html looks bad in mobile view; while you're messing around with <details> CSS make sure that's fixed

**Pull request merged**
