### PR TITLE
Update talks.html for autumn 2020

### PR DESCRIPTION
**Pull request by AaronC81**
Moves the last set of talks to _Past talks_, and adds the new talks for Autumn Term 2020.

Review of the content to check I've not got anything wrong is much appreciated but **please don't merge yet**, I haven't tested building the site!

### CODE REVIEW

**Review by FromAnkyra — COMMENTED** [review]
looks good, although this does remind me of luke's point that we should probably find a better way to deal with past talks

**Comment by sersorrel** [comment]
this brings up the issue of year numbering – for the sake of example, what should we call the three terms of last academic year?

"autumn 2019", "spring 2020", "summer 2020" is what's implied by this PR; i think that this is confusing and that we should use either "autumn/spring/summer 2020" or "autumn/spring/summer 2019/20" instead, i'm but open to opinions from others (or maybe we already use the "19/20/20" numbering elsewhere and i haven't noticed).

**Comment by AaronC81** [comment]
That's very true - my personal preference would be "2019/20" since that's completely unambiguous but also consistent

**Comment by AaronC81** [comment]
This renders fine after a few tiny tweaks, so I'll merge it in

**Comment by AaronC81** [comment]
...whoops

**Pull request merged**
