### PR TITLE
Add Discord invite to irc.html

### PR DESCRIPTION
**Pull request by sersorrel**
Several freshers (amongst others) have mentioned that Slack doesn't work well for them. It seems like it's probably worth advertising that we have a Discord server for those that don't want to use Slack.

I'm open to changes to the wording. I'm also not really happy with the layout, the noticebox feels too big:

image

### CODE REVIEW

**Comment by sersorrel** [comment]
Changes made per committee meeting.

**Review by FromAnkyra — COMMENTED** [review]
> there's also an invite in #gaming in slack

there's also an invite in #general, should we not point to that (as it's less effort)?

**Comment by sersorrel** [comment]
i failed to notice the one in general :upside_down_face: updated the PR

**Comment by FromAnkyra** [comment]
rip, other observation: should the thumbnail be changed from slack/irc to something else? (probably not slack/irc/discord but)

**Comment by sersorrel** [comment]
hhhh

inclined to not bother ~given the page is still called irc.html~ but idk

@HackSoc/2020-21-committee have opinions

**Comment by LukeMoll** [comment]
I'm pretty happy with the wording, great job! 
WRT box creep, maybe we could move the #cs-york note to the IRC paragraph?
It's probably fine to leave the navbar link as Slack/IRC chat, I noticed that the <title> is still IRC. In any case, this should probably reflect the navbar link (ie, change to Slack/IRC if we leave the navbar link). Alternatively we could unify everything as "chat" or "text chat", as long as that isn't too vague.
Now that Discord is a bit more "official", at some point we might could the #general link (maybe replace with a pinned message) &ndash; the important slack &rarr; discord movement is for VGAC/Film Night, which Aaron includes an invite to in the announcement messages.

---

_&ldquo;We are HackSoc. Our primary communication method is Slack &ndash; and IRC. Our two communcation methods are Slack and IRC and Di &ndash; Our three ways of communcating are Slack, IRC, and Discord&rdquo;_
still image from Monty Python "the Spanish Inquisition" sketch

**Review by JMAlego — APPROVED** [review]
The changes seem find, though I agree we probably do need a nicer solution at some point given it is a rather large box at this point.

**Comment by sersorrel** [comment]
- title changed
- #cs-york paragraph is not in the box any more

image

**Review by LukeMoll — APPROVED** [review]
Looks good to me!

**Review by FromAnkyra — APPROVED** [review]

**Pull request merged**
